"""website_link  migration

Revision ID: 48be81ae7966
Revises: 84a05b98844a
Create Date: 2022-07-02 14:04:36.358180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48be81ae7966'
down_revision = '84a05b98844a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
