"""back_populates  migration

Revision ID: 659fd2eed693
Revises: 48be81ae7966
Create Date: 2022-07-02 15:22:44.601640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659fd2eed693'
down_revision = '48be81ae7966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('show_id', sa.Integer(), nullable=True))
    op.alter_column('artists', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'artists', 'shows', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.alter_column('artists', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('artists', 'show_id')
    # ### end Alembic commands ###
