"""back_populates  migration

Revision ID: 70956ab188d4
Revises: 4210f7e17104
Create Date: 2022-07-04 16:57:13.560451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70956ab188d4'
down_revision = '4210f7e17104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artists_venue_id_fkey', 'artists', type_='foreignkey')
    op.drop_column('artists', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artists_venue_id_fkey', 'artists', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###
