"""foreign key  migration

Revision ID: 8f34a47b9e2b
Revises: d61615268d70
Create Date: 2022-06-30 18:35:59.604791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f34a47b9e2b'
down_revision = 'd61615268d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('show_id', sa.Integer(), nullable=False))
    op.add_column('artists', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'artists', 'shows', ['show_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artists', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.add_column('venues', sa.Column('show_id', sa.Integer(), nullable=False))
    op.add_column('venues', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venues', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'venues', 'shows', ['show_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'artist_id')
    op.drop_column('venues', 'show_id')
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'venue_id')
    op.drop_column('artists', 'show_id')
    # ### end Alembic commands ###
